# General configuration
[general]
import = [
    "~/.config/alacritty/themes/aura-theme.toml"
]

# Window settings
[window]
  dimensions = { columns = 100, lines = 90 }
  position = { x = 0, y = 0 }
  opacity = 0.85
  decorations = "full"
  dynamic_padding = true

# Font configuration
[font]
  normal = { family = "Hack", style = "Regular" }
  bold   = { family = "Hack", style = "Bold" }
  italic = { family = "Hack", style = "Italic" }
  size = 10.0

# Scrolling settings
[scrolling]
  history = 10000
  multiplier = 3

# Mouse settings
[mouse]
  hide_when_typing = true

# Keybindings
